Fixes for 10.0
stako/sArena pull request #66
Opened 2022-10-29 12:10 UTC by MyGamesDevelopmentAcc

Wasn't making any updates to spells, just modified it so it works without errors. Did some testing, haven't noticied any errors.

Changes:
Changes required by new handling of cast bar. Kept back compatiblity with color setting as much as I could best to my knowledge

2022-10-29 17:01 UTC, MyGamesDevelopmentAcc commented
Hiding Blizzard frames does not yet work properly.

2022-10-29 17:31 UTC, MyGamesDevelopmentAcc commented
They seemto hide now, but I think there is still an issue with setting focus by mouse

2022-10-29 19:49 UTC, MyGamesDevelopmentAcc commented
The issue with focus and target is resolved.

2022-10-29 23:20 UTC, jturel commented
@MyGamesDevelopmentAcc let me know when you don't expect to push any more changes and I can test

2022-10-29 23:31 UTC, MyGamesDevelopmentAcc commented
I do not expect to push any more changes. To be honest I am not too fluent in githubish and didn't know initially that my 2nd commit through the github app will be attached automatically to this merge request, so I had to keep on rolling with it ;) Sorry about that.

2022-10-29 23:38 UTC, jturel commented
> I do not expect to push any more changes. To be honest I am not too fluent in githubish and didn't know initially that my 2nd commit through the github app will be attached automatically to this merge request, so I had to keep on rolling with it ;) Sorry about that.

no worries. pushing to the branch that you created this PR from also updates the PR!

2022-10-30 01:27 UTC, jturel requested changes
Thank you @MyGamesDevelopmentAcc - this is a big improvement!

I left a few comments - mostly around using tab indentation vs space indentation. Better to be consistent with what's already there :)

2022-10-30 01:27 UTC, jturel commented on sArena.toc
> +## Version: 3.1.9
Make this 3.2 to signify a more significant change (backward incompatible with old version)

2022-10-30 01:27 UTC, jturel commented on sArena.xml
> +		<Scripts>
Tab indentation

2022-10-30 01:27 UTC, jturel commented on sArena.lua
> +    --f:SetStatusBarTexture(nil)
What do you think about just deleting this line?

2022-10-30 01:27 UTC, jturel commented on sArena.lua
> +	self.CastBar:SetUnit(unit, false, true)
Tab

2022-10-30 01:27 UTC, jturel commented on sArena.lua
> +    --if ( not IsAddOnLoaded("Blizzard_ArenaUI") ) then return end
Delete this, or keep?

2022-10-30 01:27 UTC, jturel commented on Layouts/Xaryu.lua
> +	frame.CastBar.typeInfo = {
Tab indentation

2022-10-30 01:27 UTC, jturel commented on Layouts/BlizzTourney.lua
> +	f.typeInfo = {
Tab indentation

2022-10-30 01:27 UTC, jturel commented on Layouts/BlizzTarget.lua
> +	f.typeInfo = {
Tab indentation

2022-10-30 01:27 UTC, jturel commented on Layouts/BlizzArena.lua
> +	local typeInfoTexture = "Interface\\TargetingFrame\\UI-StatusBar";
Tab indentation

2022-10-30 13:16 UTC, MyGamesDevelopmentAcc commented
@jturel I have made the requested fixes, added some further formatting at the end, fixed further problems found with WoW10 handling of SecureActionButtons in certain setups.

2022-10-30 16:43 UTC, jturel commented
> I am also thinking that this will most likely break, if there was, the compatiblity with older Wow versions as I have not added any special handling to distinguish whether this is wow10 or not.

As far as I'm aware the "retail" version of sArena has supported only the latest wow version!

2022-10-30 16:58 UTC, jturel commented
This got a lot harder to review because of all the extra formatting changes that got included. I'll need some time :)

2022-10-30 17:54 UTC, MyGamesDevelopmentAcc commented
For that reason I have done it in separate commits, hoping it will be easier to see which was changed/modified in each.

2022-10-30 18:33 UTC, jturel commented
@MyGamesDevelopmentAcc i fixed an automatic action that should run in this repo to validate the lua syntax automatically. Can you do me a favor and rebase your branch against the master branch? After you push, you'll see the job run here and tell you whether it passes or fails.

Your steps would look something like the below, given a remote called 'origin' corresponding to this repo (not your fork):

```
git fetch origin
git rebase origin/master
git push $YOUR_FORK_REMOTE $YOUR_BRANCH_NAME --force
```

2022-10-30 20:48 UTC, MyGamesDevelopmentAcc commented
Added two new globals and rebased. Please let me know if this is what you asked for.

2022-10-30 20:50 UTC, jturel commented on .luacheckrc
> +    'ArenaEnemyFramesContainer',
This looks good. Can you put these at the top of the file? They seem to be in alphabetical order :)

2022-10-30 23:51 UTC, jturel commented
Thank you @MyGamesDevelopmentAcc ! Unfortunately this is as far as I can help you as I don't have the ability to create a new release on Curse. Merging this.

2022-10-30 23:51 UTC, jturel approved these changes

2022-10-30 23:51 UTC, merged

2022-10-31 08:53 UTC, MyGamesDevelopmentAcc commented
@stako any chances for you to release? @jturel maybe we can add release format which could be picked by wowup?

2022-12-10 22:17 UTC, jturel commented
> @stako any chances for you to release this please? @jturel maybe we can add release format which could be picked by wowup?

hey there @MyGamesDevelopmentAcc - missed this message. I'm happy to review and test any changes to get the addon picked up by wowup :)